name: no_exif
version: 0.9.2
author: Peter Siroki <psiroki@skawa.hu>
description: A simple example for the image_whisperer library
homepage: https://github.com/skawa-universe/no_exif

dependencies:
  pool:
  image_whisperer:
    git:
      url: https://github.com/skawa-universe/image_whisperer.git
  dart_to_js_script_rewriter:
transformers:
- $dart2js:
    minify: true
    csp: true
- dart_to_js_script_rewriter
